# Flask configuration
DEBUG = True
SECRET_KEY = 'XyE45w0:hD!5oeRq@_UV&2wA8sB'
SESSION_COOKIE_NAME = 'botran'

BOTRAN_ID = 'Y2lzY29zcGFyazovL3VzL1BFT1BMRS9jYmM4YzljOS1jNDZjLTRlNjEtODllMi1iZmQ5YzhiYjE4ZTY'
BOTRAN_APP_ID = 'Y2lzY29zcGFyazovL3VzL0FQUExJQ0FUSU9OL0MzMmM4MDc3NDBjNmU3ZGYxMWRhZjE2ZjIyOGRmNjI4YmJjYTQ5YmE1MmZlY2JiMmM3ZDUxNWNiNGEwY2M5MWFh'
BOTRAN_SECRET_KEY='MDczMDJlN2YtN2EwYy00NGQwLWI1ZTAtNjE3NGJmN2EzYTNlZTM0OGZhMzEtYTIx'
BOTRAN_TARGET_URL = 'https://2c8fcd6b.ngrok.io'
BOTRAN_CONTACT = 'botran@sparkbot.io'
BOTRAN_WEBHOOK_NAME = 'Botran Webhook'
BOTRAN_NAME = 'Botran'
