# Flask configuration
DEBUG = True
SECRET_KEY = '<FLASK_SECRET_KEY>'
SESSION_COOKIE_NAME = 'botran'

BOTRAN_ID = '<BOTRAN_ID>'
BOTRAN_APP_ID = '<APP_ID>'
BOTRAN_SECRET_KEY='<BOTRAN_SECRET_KEY>'
BOTRAN_TARGET_URL = '<BOTRAN_WEBHOOK>'
BOTRAN_CONTACT = '<BOTRAN_CONTACT>'
BOTRAN_WEBHOOK_NAME = '<BOTRAN_WEBHOOK_NAME>'
BOTRAN_NAME = 'Botran'
